disease(migraine, head, [headache, nausea, sensitivity_to_light], 85).
disease(meningitis, head, [headache, stiff_neck, fever], 90).
disease(vertigo, head, [dizziness, balance_issues, blurred_vision], 80).
disease(sinusitis, head, [facial_pain, sinus_pressure, congestion], 75).
disease(temporal_arteritis, head, [throbbing_pain, jaw_pain, blurred_vision], 70).
disease(alopecia_areata, head, [scalp_tenderness, itching, hair_loss], 65).
disease(conjunctivitis, head, [eye_pain, redness, tearing], 75).
disease(otitis_media, head, [ear_pain, hearing_loss, discharge], 80).
disease(labyrinthitis, head, [ear_pain, tinnitus, dizziness], 78).
disease(mononucleosis, head, [swollen_glands, sore_throat, fatigue], 85).
disease(myasthenia_gravis, head, [double_vision, drooping_eyelid, difficulty_swallowing], 70).
disease(tmj_disorder, head, [jaw_pain, earache, clicking_sound], 75).
disease(cluster_headache, head, [headache, scalp_sensitivity, pain_behind_eyes], 88).
disease(psoriasis, head, [itching, redness, scaling], 60).
disease(stroke, head, [facial_droop, slurred_speech, weakness], 95).
disease(multiple_sclerosis, head, [numbness, tingling, muscle_weakness], 80).
disease(brain_tumor, head, [headache, vision_changes, vomiting], 85).
disease(acoustic_neuroma, head, [dizziness, tinnitus, hearing_loss], 70).
disease(allergic_rhinitis, head, [runny_nose, sneezing, itchy_eyes], 75).
disease(herpes_zoster, head, [painful_lesions, blisters, burning_sensation], 80).
disease(acute_glaucoma, head, [sudden_vision_loss, eye_pain, nausea], 85).
disease(laryngeal_cancer, head, [persistent_cough, shortness_of_breath, hoarseness], 78).
disease(nasal_polyps, head, [loss_of_smell, nasal_obstruction, nosebleeds], 65).
disease(uveitis, head, [red_eye, haloes_around_lights, eye_pain], 70).
disease(chronic_rhinosinusitis, head, [nasal_congestion, loss_of_smell, postnasal_drip], 80).
disease(bruxism, head, [jaw_stiffness, jaw_clicking, facial_pain], 68).
disease(menieres_disease, head, [ear_fullness, tinnitus, vertigo], 75).
disease(occipital_neuralgia, head, [visual_disturbances, headache, nausea], 72).
disease(brain_aneurysm, head, [double_vision, difficulty_speaking, weakness_on_one_side], 85).
disease(subarachnoid_hemorrhage, head, [severe_headache, stiff_neck, confusion], 92).
disease(swimmers_ear, head, [earache, pain_when_swallowing, redness_in_ear], 78).
disease(sensorineural_hearing_loss, head, [sudden_hearing_loss, dizziness, ear_fullness], 85).
disease(horners_syndrome, head, [eyelid_drooping, fatigue, double_vision], 75).
disease(migraine_with_aura, head, [headache, nausea, visual_aura], 80).
disease(status_migrainosus, head, [severe_throbbing_pain, light_sensitivity, vomiting], 88).
disease(hyperemesis_gravidarum, head, [nausea, vomiting, irritability], 70).
disease(scarlet_fever, head, [sore_throat, fever, rash], 75).
disease(orbital_cellulitis, head, [painful_eye_movement, double_vision, drooping_eyelid], 82).
disease(seborrheic_dermatitis, head, [persistent_itch, flaky_skin, redness], 65).
disease(optic_neuritis, head, [vision_loss, pain_on_eye_movement, color_desaturation], 75).
disease(cerebral_palsy, head, [facial_numbness, difficulty_speaking, weakness_in_limbs], 78).
disease(tinnitus, head, [ringing_in_ears, hearing_loss, balance_problems], 70).
disease(cellulitis, head, [swelling, pain, redness], 80).
disease(thyroid_cancer, head, [persistent_cough, hoarseness, lump_in_neck], 78).
disease(ringworm, head, [scalp_itch, white_patches, hair_loss], 65).
disease(scabies, head, [intense_itching, small_bumps, blisters], 75).
disease(anaphylaxis, head, [difficulty_breathing, swollen_tongue, hives], 90).
disease(intracranial_hypertension, head, [persistent_headache, blurred_vision, seizures], 85).
disease(encephalopathy, head, [memory_loss, confusion, poor_coordination], 80).
disease(tia, head, [sudden_weakness, drooping_face, difficulty_speaking], 85).
disease(sjogrens_syndrome, head, [persistent_fatigue, dry_mouth, dry_eyes], 70).
disease(dental_abscess, head, [facial_swelling, tooth_pain, sensitivity_to_hot_cold], 80).
disease(jaw_dislocation, head, [jaw_pain, clicking_jaw, jaw_locking], 75).
disease(giant_cell_arteritis, head, [sudden_severe_headache, stiff_neck, vision_problems], 88).
disease(bells_palsy, head, [swelling, drooping_face, weakness_in_arm_leg], 78).
disease(osteomyelitis_of_jaw, head, [pain_in_jaw, swelling_in_jaw, loose_teeth], 80).
disease(common_cold, head, [runny_nose, sneezing, sore_throat], 60).
disease(mumps, head, [difficulty_chewing, swelling_in_face, fever], 75).
disease(tonsillitis, head, [persistent_sore_throat, difficulty_swallowing, ear_pain], 70).
disease(hypothyroidism, head, [puffy_face, weight_gain, fatigue], 75).
disease(trigeminal_neuralgia, head, [severe_pain_in_face, redness, blurred_vision], 80).
disease(rosacea, head, [redness, burning_sensation, small_bumps], 65).


disease(thyroiditis, neck, [neck_swelling, fatigue, difficulty_swallowing], 80).
disease(neck_strain, neck, [neck_pain, stiffness, muscle_spasms], 75).
disease(thyroid_cancer, neck, [neck_swelling, hoarseness, difficulty_swallowing], 85).
disease(cervical_spondylosis, neck, [neck_pain, stiffness, headache], 70).
disease(laryngitis, neck, [sore_throat, hoarseness, difficulty_speaking], 65).
disease(lymphadenopathy, neck, [swollen_lymph_nodes, fever, night_sweats], 78).
disease(whiplash, neck, [neck_pain, dizziness, shoulder_pain], 72).
disease(tracheitis, neck, [cough, fever, difficulty_breathing], 68).
disease(goiter, neck, [neck_swelling, difficulty_swallowing, cough], 77).
disease(tonsillitis, neck, [sore_throat, difficulty_swallowing, fever], 74).
disease(neck_abscess, neck, [neck_swelling, redness, fever], 82).
disease(pharyngitis, neck, [sore_throat, difficulty_swallowing, cough], 70).
disease(rheumatoid_arthritis, neck, [joint_pain, neck_stiffness, fatigue], 75).
disease(spinal_stenosis, neck, [neck_pain, numbness, weakness_in_arms], 80).
disease(cervical_disc_herniation, neck, [neck_pain, radiating_pain_to_arms, numbness], 85).
disease(epiglottitis, neck, [sore_throat, difficulty_swallowing, drooling], 88).
disease(torticollis, neck, [neck_twisting, neck_pain, limited_mobility], 78).
disease(sialadenitis, neck, [swollen_salivary_glands, dry_mouth, fever], 73).
disease(neck_fracture, neck, [severe_neck_pain, swelling, difficulty_moving_neck], 90).
disease(cervical_lymphadenitis, neck, [swollen_lymph_nodes, pain_in_neck, fever], 75).
disease(thoracic_outlet_syndrome, neck, [neck_pain, numbness_in_arms, swelling], 70).
disease(benign_lymphadenopathy, neck, [neck_swelling, tender_lymph_nodes, fever], 68).
disease(mastoiditis, neck, [neck_swelling, ear_pain, fever], 80).
disease(retropharyngeal_abscess, neck, [difficulty_swallowing, fever, neck_swelling], 82).
disease(dissecting_carotid_aneurysm, neck, [neck_pain, headache, drooping_eyelid], 85).
disease(supraglottitis, neck, [sore_throat, difficulty_breathing, drooling], 87).
disease(peritonsillar_abscess, neck, [severe_throat_pain, fever, neck_swelling], 83).
disease(pleomorphic_adenoma, neck, [painless_neck_mass, difficulty_swallowing, hoarseness], 72).
disease(neck_cellulitis, neck, [redness, swelling, warmth_in_neck], 78).
disease(reactive_lymphadenopathy, neck, [swollen_lymph_nodes, tenderness, fever], 69).
disease(cervical_myelopathy, neck, [neck_pain, weakness_in_arms, gait_difficulty], 81).
disease(anterior_cervical_discitis, neck, [neck_pain, fever, limited_mobility], 79).
disease(submandibular_sialadenitis, neck, [swelling_under_jaw, pain_when_eating, fever], 74).
disease(parotitis, neck, [swelling_in_jaw_area, dry_mouth, fever], 76).
disease(neck_lipoma, neck, [soft_neck_lump, painless, slow_growth], 65).
disease(neck_fibroma, neck, [firm_neck_mass, non_tender, slow_growth], 67).
disease(spinal_infection, neck, [neck_pain, fever, limited_mobility], 84).
disease(dystonia, neck, [muscle_spasms, neck_twisting, head_tilt], 75).
disease(neck_sprain, neck, [neck_pain, stiffness, limited_mobility], 70).
disease(acromegaly, neck, [enlarged_jaw, neck_pain, headache], 78).
disease(hypothyroidism, neck, [neck_swelling, fatigue, weight_gain], 77).
disease(hyperthyroidism, neck, [neck_swelling, rapid_heartbeat, weight_loss], 80).
disease(cervical_rib_syndrome, neck, [neck_pain, tingling_in_fingers, weakness_in_arms], 74).
disease(neck_myositis, neck, [muscle_pain, stiffness, swelling], 70).
disease(anterior_neck_mass, neck, [visible_lump, pain_when_swallowing, hoarseness], 79).
disease(laryngeal_cancer, neck, [hoarseness, neck_mass, difficulty_swallowing], 82).
disease(dissecting_aneurysm, neck, [sudden_neck_pain, difficulty_breathing, hoarseness], 86).
disease(spinal_osteophytes, neck, [neck_pain, tingling_in_hands, muscle_weakness], 73).
disease(cervical_rib, neck, [neck_pain, arm_pain, numbness_in_fingers], 72).
disease(cervical_herpes_zoster, neck, [neck_rash, burning_sensation, tingling], 77).
disease(neck_dermatitis, neck, [itchy_rash, redness, scaling], 68).
disease(neck_panniculitis, neck, [tender_skin_nodules, swelling, redness], 70).
disease(spinal_osteomyelitis, neck, [severe_neck_pain, fever, difficulty_moving_neck], 83).
disease(epidural_abscess, neck, [severe_neck_pain, fever, neurological_deficits], 85).
disease(neck_hemangioma, neck, [soft_lump, bluish_color, pain_on_touch], 67).
disease(brachial_neuritis, neck, [shoulder_pain, arm_weakness, neck_pain], 76).
disease(thyroglossal_duct_cyst, neck, [midline_neck_mass, pain_when_swallowing, hoarseness], 74).
disease(cervical_fibrositis, neck, [neck_pain, stiffness, muscle_tenderness], 71).
disease(neck_trauma, neck, [neck_pain, swelling, difficulty_breathing], 88).
disease(neck_hematoma, neck, [swelling, bruising, pain], 79).
disease(scalene_myositis, neck, [neck_pain, swelling, tenderness], 71).
disease(neck_lymphoma, neck, [painless_neck_mass, night_sweats, fever], 82).
disease(sarcoidosis, neck, [swollen_lymph_nodes, cough, chest_pain], 76).
disease(neck_thrombophlebitis, neck, [neck_swelling, pain, fever], 75).
disease(neck_fibromatosis, neck, [firm_lump, non_tender, slow_growth], 67).
disease(spinal_tumor, neck, [persistent_neck_pain, weakness_in_limbs, numbness], 84).
disease(neck_cyst, neck, [soft_mass, pain_when_moving_neck, tenderness], 69).
disease(neck_arteritis, neck, [neck_pain, headache, vision_problems], 81).
disease(thyroid_nodule, neck, [painless_lump, hoarseness, difficulty_swallowing], 76).
disease(scleroderma, neck, [tight_skin, difficulty_swallowing, stiffness], 72).
disease(dystonia_cervical, neck, [neck_muscle_spasms, head_tilt, pain], 75).
disease(syringomyelia, neck, [neck_pain, weakness_in_arms, numbness], 83).
disease(neck_varicose_veins, neck, [swollen_veins, pain, tenderness], 70).
disease(tuberculous_lymphadenitis, neck, [swollen_lymph_nodes, fever, night_sweats], 78).
disease(neck_abscess_formation, neck, [swelling, pain, fever], 81).
disease(cervical_cord_compression, neck, [neck_pain, paralysis, loss_of_bladder_control], 89).
disease(brachial_plexus_injury, neck, [shoulder_pain, arm_weakness, neck_stiffness], 78).
disease(bow_hunter_syndrome, neck, [neck_pain, vertigo, dizziness], 73).
disease(neck_neurofibroma, neck, [soft_mass, tenderness, nerve_pain], 71).
disease(cervical_dystonia, neck, [muscle_spasms, head_tilt, pain], 75).
disease(cervical_rib_with_compression, neck, [neck_pain, arm_numbness, tingling], 76).
disease(neck_torticollis, neck, [neck_twisting, muscle_spasms, limited_mobility], 72).
disease(juvenile_dermatomyositis, neck, [muscle_weakness, skin_rash, neck_pain], 78).
disease(cervical_bone_fracture, neck, [severe_pain, swelling, limited_mobility], 90).
disease(acute_retropharyngeal_abscess, neck, [difficulty_swallowing, fever, neck_swelling], 84).
disease(cervical_dysplasia, neck, [abnormal_cells_on_cervix, neck_pain, irregular_bleeding], 74).
disease(neck_bruise, neck, [discoloration, tenderness, swelling], 65).
disease(neck_hyperextension_injury, neck, [neck_pain, limited_mobility, muscle_spasms], 82).
disease(cervical_spondylolisthesis, neck, [neck_pain, numbness_in_arms, difficulty_walking], 86).
disease(neck_meningitis, neck, [stiff_neck, headache, fever], 89).
disease(spondylosis_of_the_neck, neck, [neck_pain, stiffness, headache], 73).


% Diseases and Symptoms for Chest Area
disease(angina, chest, [chest_pain, shortness_of_breath, sweating], 85).
disease(myocardial_infarction, chest, [severe_chest_pain, nausea, left_arm_pain], 90).
disease(pneumonia, chest, [cough, fever, chest_pain], 82).
disease(pleuritis, chest, [sharp_chest_pain, cough, difficulty_breathing], 78).
disease(pneumothorax, chest, [sudden_chest_pain, shortness_of_breath, rapid_heartbeat], 87).
disease(heart_failure, chest, [shortness_of_breath, fatigue, swelling_in_legs], 80).
disease(pulmonary_embolism, chest, [sudden_chest_pain, difficulty_breathing, rapid_heartbeat], 88).
disease(coronary_artery_disease, chest, [chest_pain, shortness_of_breath, fatigue], 83).
disease(asthma, chest, [wheezing, chest_tightness, shortness_of_breath], 75).
disease(bronchitis, chest, [persistent_cough, chest_discomfort, mucus_production], 70).
disease(pulmonary_hypertension, chest, [chest_pain, shortness_of_breath, fatigue], 78).
disease(costochondritis, chest, [chest_pain, tenderness, pain_when_breathing], 74).
disease(pleural_effusion, chest, [chest_pain, shortness_of_breath, cough], 79).
disease(pericarditis, chest, [sharp_chest_pain, fever, difficulty_breathing], 81).
disease(tuberculosis, chest, [persistent_cough, chest_pain, weight_loss], 77).
disease(acute_bronchitis, chest, [cough, chest_pain, fatigue], 72).
disease(emphysema, chest, [shortness_of_breath, chest_tightness, wheezing], 76).
disease(gerd, chest, [heartburn, chest_pain, regurgitation], 73).
disease(hiatal_hernia, chest, [chest_pain, heartburn, difficulty_swallowing], 71).
disease(pulmonary_fibrosis, chest, [shortness_of_breath, dry_cough, fatigue], 80).
disease(panic_attack, chest, [chest_pain, rapid_heartbeat, sweating], 74).
disease(pneumothorax_spontaneous, chest, [sudden_chest_pain, shortness_of_breath, fatigue], 85).
disease(cardiomyopathy, chest, [chest_pain, shortness_of_breath, fatigue], 79).
disease(aortic_dissection, chest, [sudden_chest_pain, back_pain, shortness_of_breath], 89).
disease(pulmonary_edema, chest, [chest_pain, difficulty_breathing, cough_with_frothy_sputum], 86).
disease(pleural_mesothelioma, chest, [chest_pain, shortness_of_breath, weight_loss], 82).
disease(lung_cancer, chest, [persistent_cough, chest_pain, weight_loss], 88).
disease(coronary_spasm, chest, [chest_pain, rapid_heartbeat, shortness_of_breath], 84).
disease(rib_fracture, chest, [sharp_chest_pain, pain_when_breathing, tenderness], 81).
disease(lung_abscess, chest, [chest_pain, cough_with_pus, fever], 77).
disease(pericardial_effusion, chest, [chest_pain, shortness_of_breath, rapid_heartbeat], 83).
disease(myocarditis, chest, [chest_pain, fatigue, shortness_of_breath], 79).
disease(tracheitis, chest, [chest_discomfort, cough, difficulty_breathing], 72).
disease(bronchiectasis, chest, [persistent_cough, chest_pain, mucus_production], 75).
disease(collapse_of_lung, chest, [sharp_chest_pain, shortness_of_breath, rapid_heartbeat], 86).
disease(thoracic_aortic_aneurysm, chest, [chest_pain, back_pain, difficulty_swallowing], 87).
disease(pleural_thickening, chest, [chest_pain, shortness_of_breath, dry_cough], 76).
disease(thoracic_spine_fracture, chest, [severe_chest_pain, back_pain, difficulty_moving], 80).
disease(lung_fibrosis, chest, [shortness_of_breath, chest_tightness, dry_cough], 78).
disease(tracheobronchitis, chest, [chest_pain, persistent_cough, fever], 73).
disease(upper_lobe_pneumonia, chest, [chest_pain, cough, fever], 82).
disease(sarcoidosis, chest, [chest_pain, shortness_of_breath, skin_rash], 77).
disease(heart_valve_disease, chest, [chest_pain, shortness_of_breath, palpitations], 81).
disease(lung_atelectasis, chest, [chest_pain, difficulty_breathing, cough], 83).
disease(mediastinitis, chest, [severe_chest_pain, fever, difficulty_breathing], 85).
disease(cystic_fibrosis, chest, [persistent_cough, chest_pain, difficulty_breathing], 78).
disease(pleural_tumor, chest, [chest_pain, shortness_of_breath, cough], 80).
disease(boerhaave_syndrome, chest, [severe_chest_pain, vomiting, shortness_of_breath], 89).
disease(thoracic_outlet_syndrome, chest, [chest_pain, shoulder_pain, numbness_in_arm], 75).
disease(asbestosis, chest, [chest_pain, shortness_of_breath, cough], 76).
disease(pulmonary_emphysema, chest, [chest_pain, difficulty_breathing, wheezing], 77).
disease(ischemic_heart_disease, chest, [chest_pain, shortness_of_breath, fatigue], 85).
disease(bronchiolitis, chest, [chest_discomfort, cough, shortness_of_breath], 70).
disease(diaphragmatic_hernia, chest, [chest_pain, difficulty_breathing, abdominal_pain], 78).
disease(pericardial_tamponade, chest, [severe_chest_pain, shortness_of_breath, rapid_heartbeat], 86).
disease(lung_embolism, chest, [chest_pain, shortness_of_breath, coughing_up_blood], 87).
disease(pneumocystis_pneumonia, chest, [cough, chest_pain, shortness_of_breath], 79).
disease(pleural_empyaema, chest, [chest_pain, fever, difficulty_breathing], 82).
disease(congestive_heart_failure, chest, [chest_pain, shortness_of_breath, swelling_in_legs], 85).
disease(bronchogenic_carcinoma, chest, [chest_pain, persistent_cough, weight_loss], 86).
disease(musculoskeletal_chest_pain, chest, [chest_tenderness, pain_with_movement, muscle_spasms], 71).
disease(hemothorax, chest, [chest_pain, difficulty_breathing, rapid_heartbeat], 84).
disease(lung_abscess_chronic, chest, [chronic_chest_pain, cough_with_pus, fever], 80).
disease(pleurisy, chest, [sharp_chest_pain, dry_cough, difficulty_breathing], 78).
disease(thoracic_herpes_zoster, chest, [chest_pain, rash, tingling_sensation], 73).
disease(lung_contusion, chest, [chest_pain, cough, shortness_of_breath], 82).
disease(thoracic_spinal_stenosis, chest, [chest_pain, back_pain, difficulty_walking], 77).
disease(pulmonary_alveolar_proteinosis, chest, [cough, chest_pain, shortness_of_breath], 74).
disease(acute_respiratory_distress_syndrome, chest, [severe_chest_pain, shortness_of_breath, rapid_heartbeat], 89).
disease(restrictive_cardiomyopathy, chest, [chest_pain, shortness_of_breath, fatigue], 80).
disease(bacterial_pneumonia, chest, [chest_pain, cough, fever], 83).
disease(interstitial_lung_disease, chest, [chest_pain, dry_cough, shortness_of_breath], 79).
disease(bullous_lung_disease, chest, [chest_pain, shortness_of_breath, difficulty_breathing], 76).
disease(pancoast_tumor, chest, [chest_pain, shoulder_pain, arm_pain], 84).
disease(eosinophilic_pneumonia, chest, [chest_pain, cough, shortness_of_breath], 78).
disease(lung_bullae, chest, [chest_pain, shortness_of_breath, fatigue], 72).
disease(pulmonary_consolidation, chest, [chest_pain, cough, fever], 83).
disease(ventricular_fibrillation, chest, [chest_pain, rapid_heartbeat, shortness_of_breath], 87).
disease(pericardial_cyst, chest, [chest_pain, shortness_of_breath, cough], 75).
disease(scleroderma_lung, chest, [chest_pain, shortness_of_breath, skin_thickening], 78).
disease(swyer_james_syndrome, chest, [chest_pain, shortness_of_breath, chronic_cough], 73).
disease(spontaneous_pneumomediastinum, chest, [chest_pain, difficulty_breathing, neck_swelling], 84).
disease(pleural_plaque, chest, [chest_pain, shortness_of_breath, cough], 71).
disease(pulmonary_cavity, chest, [chest_pain, cough, fever], 76).
disease(pneumoconiosis, chest, [chest_pain, shortness_of_breath, chronic_cough], 74).
disease(pleural_fibrosis, chest, [chest_pain, shortness_of_breath, chronic_cough], 75).
disease(hypersensitivity_pneumonitis, chest, [chest_pain, shortness_of_breath, fatigue], 78).
disease(lung_granuloma, chest, [chest_pain, cough, fatigue], 79).
disease(tracheobronchomalacia, chest, [chest_pain, difficulty_breathing, chronic_cough], 81).